const express = require("express");
require("dotenv").config();
const cors = require("cors");
const userRoutes = require("./routes/userRoutes.js");
const studentRoutes = require("./routes/studentRoutes.js");
const employeeRoutes = require("./routes/employeeRoutes.js");
const parentRoutes = require("./routes/parentRoutes.js");
const sessionRoutes = require("./routes/sessionRoutes.js");
const classRoutes = require("./routes/classRoutes.js");
const academicCalenderRoutes = require("./routes/academicCalenderRoutes.js");
const sectionRoutes = require("./routes/sectionRoutes.js");
const categoryRoutes = require("./routes/categoryRoutes.js");
const departmentRoutes = require("./routes/departmentRoutes.js");
const desiginationRoutes = require("./routes/desiginationRoutes.js");
const gradeRoutes = require("./routes/gradeRoutes.js");
const feeRoutes = require("./routes/feeRoutes.js");
const religionRoutes = require("./routes/religionRoutes.js");
const subjectRoutes = require("./routes/subjectRoutes.js");
const transportationRoutes = require("./routes/transportationRoutes.js");
const examGradeRoutes = require("./routes/examGradeRoutes.js");
const examScheduleRoutes = require("./routes/examScheduleRoutes.js");
const examCategoryRoutes = require("./routes/examCategoryRoutes.js");
const noticeBoardRoutes = require("./routes/noticeBoardRoutes.js");
const extraClassesRoutes = require("./routes/extraClassesRoutes.js");
const classScheduleRoutes = require("./routes/classScheduleRoutes.js");
const assignSubjectToTeacherRoutes = require("./routes/assignSubjectToTeacherRoutes.js");
const adminRoutes = require("./routes/adminRoutes.js");
const calendarRoutes = require("./routes/calendarRoutes.js");
const studyMaterialRoutes = require("./routes/studyMaterialRoutes.js");
const syllabusRoutes = require("./routes/syllabusRoutes.js");
const queryRoutes = require("./routes/queryRoutes.js");
const expenseCategoryRouter = require("./routes/expenseCategoryRoutes.js");
const accountExpenseRouter = require("./routes/accountExpenseRoutes.js");
const connectDB = require("./config/db.js");
const errorHandler = require("./middlewares/errorHandlers.js");
const timeTableRoutes = require("./routes/timeTableRoutes.js");
const studentAttendanceRoutes = require("./routes/studentAttendanceRoutes.js");

connectDB();
const app = express();
// Middleware
app.use(cors());
app.use(express.json());
// Routes
app.use("/api/admin", adminRoutes);
app.use("/api/user", userRoutes);
app.use("/api/student", studentRoutes);
app.use("/api/employee", employeeRoutes);
app.use("/api/parent", parentRoutes);
app.use("/api/session", sessionRoutes);
app.use("/api/class", classRoutes);
app.use("/api/academic", academicCalenderRoutes);
app.use("/api/calendar", calendarRoutes);
app.use("/api/section", sectionRoutes);
app.use("/api/category", categoryRoutes);
app.use("/api/department", departmentRoutes);
app.use("/api/designation", desiginationRoutes);
app.use("/api/fee", feeRoutes);
app.use("/api/religion", religionRoutes);
app.use("/api/subject", subjectRoutes);
app.use("/api/grade", gradeRoutes);
app.use("/api/exam-grade", examGradeRoutes);
app.use("/api/transportation", transportationRoutes);
app.use("/api/exam-Schedule", examScheduleRoutes);
app.use("/api/exam-category", examCategoryRoutes);
app.use("/api/notice-board", noticeBoardRoutes);
app.use("/api/extra-classes", extraClassesRoutes);
app.use("/api/class-schedule", classScheduleRoutes);
app.use("/api/assign-subject-to-teacher", assignSubjectToTeacherRoutes);
app.use("/api/material", studyMaterialRoutes);
app.use("/api/syllabus", syllabusRoutes);
app.use("/api/query", queryRoutes);
app.use("/api/expense-category", expenseCategoryRouter);
app.use("/api/account-expense", accountExpenseRouter);
app.use("/api/timetable", timeTableRoutes);
app.use("/api/student-attendance", studentAttendanceRoutes);
// Error handler middleware
app.use(errorHandler);

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`Server running on port: ${PORT}`));
